import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import bcrypt from 'bcryptjs'
import { notifyAdminsAndManagers } from '@/lib/notifications'

// GET /api/pm/team - Fetch all team members
export async function GET(req: NextRequest) {
  try {
    console.log('[API /api/pm/team] GET request received')
    
    const session = await getServerSession(authOptions)
    console.log('[API /api/pm/team] Session:', session?.user?.email, 'Role:', session?.user?.role)

    if (!session?.user) {
      console.log('[API /api/pm/team] Unauthorized - no session')
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Check if user has permission (ADMIN, MANAGER, ARCHITECT, DRAFTER can view)
    const userRole = session.user.role
    if (userRole !== 'ADMIN' && userRole !== 'MANAGER' && userRole !== 'ARCHITECT' && userRole !== 'DRAFTER') {
      console.log('[API /api/pm/team] Forbidden - role:', userRole)
      return NextResponse.json({ error: 'Forbidden - Only ADMIN, MANAGER, ARCHITECT, and DRAFTER can view team' }, { status: 403 })
    }

    console.log('[API /api/pm/team] Fetching users from database...')
    
    // Fetch all users (office staff only, excluding field workers)
    const users = await prisma.user.findMany({
      select: {
        id: true,
        name: true,
        email: true,
        username: true,
        role: true,
        image: true,
        isTempPassword: true,
        createdAt: true,
        updatedAt: true,
        _count: {
          select: {
            projects: true,
          },
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    })

    console.log('[API /api/pm/team] Found', users.length, 'users')
    return NextResponse.json({ users }, { status: 200 })
  } catch (error) {
    console.error('[API /api/pm/team] Error fetching team members:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}

// POST /api/pm/team - Add new team member
export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Check if user has permission (ADMIN, MANAGER, ARCHITECT can add members)
    const userRole = session.user.role
    if (userRole !== 'ADMIN' && userRole !== 'MANAGER' && userRole !== 'ARCHITECT') {
      return NextResponse.json({ error: 'Forbidden - Only ADMIN, MANAGER, and ARCHITECT can add team members' }, { status: 403 })
    }

    const body = await req.json()
    const { name, email, username, role, password, autoGeneratePassword } = body

    // Validation
    if (!name || !email || !role) {
      return NextResponse.json(
        { error: 'Name, email, and role are required' },
        { status: 400 }
      )
    }

    // Validate role based on user's permission
    // ADMIN and MANAGER can create any role
    // ARCHITECT can only create ARCHITECT and DRAFTER
    const validRoles = ['ADMIN', 'MANAGER', 'ARCHITECT', 'DRAFTER', 'USER']
    if (!validRoles.includes(role)) {
      return NextResponse.json({ error: 'Invalid role' }, { status: 400 })
    }

    // ARCHITECT cannot create ADMIN or MANAGER
    if (userRole === 'ARCHITECT' && (role === 'ADMIN' || role === 'MANAGER')) {
      return NextResponse.json({ 
        error: 'Forbidden - ARCHITECT can only create ARCHITECT, DRAFTER, or USER roles' 
      }, { status: 403 })
    }

    // Check if email already exists
    const existingUser = await prisma.user.findUnique({
      where: { email },
    })

    if (existingUser) {
      return NextResponse.json(
        { error: 'Email already exists' },
        { status: 400 }
      )
    }

    // Check if username already exists (if provided)
    if (username) {
      const existingUsername = await prisma.user.findUnique({
        where: { username },
      })

      if (existingUsername) {
        return NextResponse.json(
          { error: 'Username already exists' },
          { status: 400 }
        )
      }
    }

    // Generate or use provided password
    let finalPassword = password
    let isAutoGenerated = false

    if (autoGeneratePassword || !password) {
      // Auto-generate password: first name + random 4 digits
      const firstName = name.split(' ')[0]
      const randomDigits = Math.floor(1000 + Math.random() * 9000)
      finalPassword = `${firstName}${randomDigits}`
      isAutoGenerated = true
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(finalPassword, 10)

    // Create user
    const newUser = await prisma.user.create({
      data: {
        name,
        email,
        username: username || null,
        role,
        password: hashedPassword,
        isTempPassword: true, // Always set to true for new accounts
      },
      select: {
        id: true,
        name: true,
        email: true,
        username: true,
        role: true,
        image: true,
        isTempPassword: true,
        createdAt: true,
      },
    })

    // Create notification for admins and managers
    try {
      console.log('[API /api/pm/team] Creating notifications for admins and managers...')
      const notificationResult = await notifyAdminsAndManagers(
        'Anggota Tim Baru',
        `${name} (${email}) telah ditambahkan ke tim sebagai ${role}`,
        'SUCCESS'
      )
      console.log('[API /api/pm/team] Notification result:', notificationResult)
    } catch (notifError) {
      // Don't fail the request if notification fails
      console.error('[API /api/pm/team] Error creating notification:', notifError)
    }

    // Return user data with plain password if auto-generated (for display to admin)
    return NextResponse.json(
      {
        user: newUser,
        ...(isAutoGenerated && { generatedPassword: finalPassword }),
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('[API /api/pm/team] Error creating team member:', error)
    return NextResponse.json(
      { 
        error: 'Internal server error',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
